version: '3'
services:
  webserver:
    image: httpd:latest
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - my_network

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my_network

  php:
    image: php:latest
    volumes:
      - ./php-code:/var/www/html
    depends_on:
      - database
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
